Repository postmanlabs/postman-runtime, pull requests merged in 2018-12, with the labels that each got.

#675 Inherit protocolProfileBehavior from parent
  lib/runner/create-item-context.js
  lib/runner/extensions/http-request.command.js
  package-lock.json
  package.json
  test/integration/request-body/protocolProfileBehavior.test.js
Labels: enhancement, tests

#677 Add tests for 307 & 308 redirects
  package-lock.json
  package.json
  test/integration/sanity/redirect.test.js
Labels: tests

#678 Add protocol profile behaviors to override requester defaults
  lib/requester/core.js
  lib/requester/requester.js
  package-lock.json
  package.json
  test/integration/protocol-profile-behavior/disableBodyPruning.test.js
  test/integration/protocol-profile-behavior/sanity.test.js
  test/unit/requester-core.test.js
Labels: enhancement, tests

#685 Greenkeeper/eslint plugin jsdoc 3.12.0
  package-lock.json
  package.json
Labels: greenkeeper

#689 Greenkeeper/eslint plugin jsdoc 3.14.0
  package-lock.json
  package.json
Labels: greenkeeper

#692 Fix flaky integration tests
  .travis.yml
  package-lock.json
  package.json
  test/integration/protocol-profile-behavior/disableBodyPruning.test.js
  test/integration/protocol-profile-behavior/sanity.test.js
  test/integration/requester-spec/redirect.test.js
  test/integration/sanity/certificate.test.js
  test/integration/sanity/content-type-in-form-data.test.js
  test/integration/sanity/http-methods.test.js
  test/integration/sanity/http-reason-phrases.test.js
  test/integration/sanity/multi-value-response-headers.test.js
  test/integration/sanity/redirect.test.js
  test/system/travis-yml.test.js
Labels: tests

#695 Fix certificate lookup error for missing key or cert
  lib/runner/request-helpers-presend.js
Labels: bug

#690 Fix issue avoiding sending request properly when URL is uppercase
  CHANGELOG.md
  lib/requester/core.js
  test/integration/request-flow/multi-case-url.test.js
  test/unit/requester-core.test.js
Labels: bug

#699 Add integration tests for sandbox libraries
  package-lock.json
  package.json
  test/integration/sandbox-libraries/ajv.test.js
  test/integration/sandbox-libraries/chai-postman.test.js
  test/integration/sandbox-libraries/pm.test.js
Labels: tests
