Repository postmanlabs/postman-runtime, pull requests merged in 2018-09, with the labels that each got.

#632 Added tests for custom HTTP method
  test/integration/sanity/http-methods.test.js
Labels: tests

#633 Added unit tests for lookupStrategy with duplicates in collection
  test/unit/extract-runnable-items.test.js
Labels: tests

#634 Added tests for missing & non-string HTTP method
  test/integration/sanity/http-methods.test.js
Labels: tests

#640 Dropped support for `sendBodyWithGetRequests` requester option
  CHANGELOG.md
  README.md
  lib/requester/core.js
  lib/requester/requester-pool.js
  test/integration/sanity/get-req-bodies.test.js
  test/unit/requester-core.test.js
Labels: breaking change

#643 Added tests for protocolProfileBehavior using HEAD & Custom request method
  appveyor.yml
  package-lock.json
  test/integration/request-body/protocolProfileBehavior.test.js
Labels: tests

#642 Greenkeeper/eslint plugin lodash 3.1.0
  package-lock.json
  package.json
Labels: greenkeeper
