Repository postmanlabs/postman-runtime, pull requests merged in 2019-01, with the labels that each got.

#718 Separating local server code from test files and use it as a module.
  test/fixtures/server.js
  test/integration/protocol-profile-behavior/disableBodyPruning.test.js
  test/integration/sanity/http-methods.test.js
Labels: tests

#719 Added SSL server to separate module in tests
  test/fixtures/server.js
  test/integration/protocol-profile-behavior/sanity.test.js
  test/integration/sanity/certificate.test.js
Labels: tests

#721 Added redirect server to separate module in tests
  test/fixtures/server.js
  test/integration/protocol-profile-behavior/sanity.test.js
  test/integration/requester-spec/redirect.test.js
  test/integration/sanity/certificate.test.js
  test/integration/sanity/redirect.test.js
Labels: tests

#722 Added HTTP server to module server.js
  test/fixtures/server.js
  test/integration/request-flow/headers.test.js
  test/integration/sanity/content-type-in-form-data.test.js
  test/integration/sanity/form-data-order.test.js
  test/integration/sanity/http-reason-phrases.test.js
  test/integration/sanity/multi-value-response-headers.test.js
Labels: tests

#723 Handle undefined in interrupted script execution
  lib/runner/extensions/event.command.js
  test/integration/sanity/control-flow.test.js
Labels: bug

#710 Test: Calculate request payload size
  package-lock.json
  package.json
  test/integration/sanity/request-size.test.js
Labels: enhancement, tests

#713 Exposed runtime version and dependencies tree via API
  lib/index.js
  lib/version.js
  package-lock.json
  package.json
  test/unit/version.test.js
Labels: enhancement
