Repository postmanlabs/postman-runtime, pull requests merged in 2019-03, with the labels that each got.

#767 Test: Updated PFX with invalid passphrase
  test/fixtures/certificates/client-pkcs12-passphrase2.pfx
  test/integration/sanity/certificate.test.js
Labels: tests

#763 Added support for extending the root CA certificates
  CHANGELOG.yaml
  README.md
  lib/requester/core.js
  lib/requester/request-wrapper.js
  lib/requester/requester-pool.js
  lib/runner/extensions/http-request.command.js
  test/integration/requester-spec/extendedRootCA.test.js
  test/unit/requester-core.test.js
Labels: enhancement

#768 Use high-resolution time to calculate `timings.offset.done`
  CHANGELOG.yaml
  lib/requester/requester.js
  package.json
Labels: bug

#775 Added tests for proxy authentication
  package-lock.json
  package.json
  test/fixtures/server.js
  test/integration/sanity/proxy-http.test.js
Labels: tests

#782 Added ability to clone file read stream
  lib/runner/request-helpers-presend.js
  lib/runner/util.js
Labels: enhancement

#783 Lint: enable space-before-function-paren
  .eslintrc
  lib/requester/request-wrapper.js
  lib/runner/instruction.js
  test/integration-legacy/requester-spec.test.js
  test/integration/auth-methods/hawk.test.js
  test/integration/inherited-entities/pm-variables.test.js
  test/integration/request-flow/headers.test.js
  test/integration/request-flow/pm-send-request-cookies.test.js
  test/integration/request-flow/requests-from-sandbox.test.js
  test/integration/requester-spec/headers.test.js
  test/integration/sanity/collection-variable.test.js
  test/integration/sanity/content-type-in-form-data.test.js
  test/integration/sanity/data-file-var-replacement.test.js
  test/integration/sanity/dns-lookup.test.js
  test/integration/sanity/esc-formdata.test.js
  test/integration/sanity/form-data-order.test.js
  test/integration/sanity/gzip-encoding.test.js
  test/integration/sanity/hawk-auth.test.js
  test/integration/sanity/multi-value-data.test.js
  test/integration/sanity/multiple-value-form-data.test.js
  test/integration/sanity/oauth1-var-in-url-params.test.js
  test/integration/sanity/redirect.test.js
  test/integration/sanity/request-errors.test.js
  test/integration/sanity/request-name-script.test.js
  test/integration/sanity/request-size.test.js
  test/integration/sanity/response-size.test.js
  test/integration/sanity/restricted-addresses.test.js
  test/integration/sanity/sandbox-libraries.test.js
  test/integration/sanity/script-result.test.js
  test/integration/sanity/set-next-request.test.js
  test/integration/sanity/slashed-variable.test.js
  test/integration/sanity/sugar-js.test.js
  test/integration/sanity/timeouts/async-scripts.test.js
  test/integration/sanity/url-sanity-before-request.test.js
  test/integration/sanity/v2-regression.test.js
  test/integration/sanity/var-overrides.test.js
  test/integration/sanity/var-replacement.test.js
  test/integration/sanity/variable-changes.test.js
  test/integration/sanity/variable-resolution.test.js
  test/unit/auth-loader.test.js
  test/unit/backpack-multiback.test.js
  test/unit/requester-core.test.js
Labels: housekeeping

#786 Add history in request and response callback
  CHANGELOG.yaml
  README.md
  lib/requester/requester.js
  lib/runner/extensions/http-request.command.js
  lib/runner/extensions/request.command.js
  package-lock.json
  package.json
  test/integration/requester-spec/timing.test.js
Labels: enhancement

#788 Update proxy auth test
  package-lock.json
  package.json
  test/integration/sanity/proxy-http.test.js
Labels: tests

#787 Add TLS protocol profile behavior
  CHANGELOG.yaml
  docs/protocol-profile-behavior.md
  lib/requester/core.js
  lib/requester/requester-pool.js
  test/fixtures/server.js
  test/integration/protocol-profile-behavior/tlsProtocols.test.js
  test/unit/requester-core.test.js
Labels: enhancement

#790 Docs: Added history
  README.md
  docs/history.md
Labels: docs
